Fix Travis CI build with Python 3.4
There may be incompatible dependencies related to six version
in jsonschema and pyrsistent. The actual root cause is not
known for sure. Trying to unpin the six version so existing
version in Travis CI Python3.4 environment could be kept.

== Clip ==

Requirement already satisfied: psycopg2-binary==2.8.2 in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from -r requirements.txt (line 6))
Collecting pyrsistent==0.14.11 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/8c/46/4e93ab8a379d7efe93f20a0fb8a27bdfe88942cc954ab0210c3164e783e0/pyrsistent-0.14.11.tar.gz (104kB)
    100% || 112kB 2.6MB/s
Requirement already satisfied: python-mimeparse==1.6.0 in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: pyyaml in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from -r requirements.txt (line 9))
Collecting six==1.12.0 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from jsonschema==3.0.1->-r requirements.txt (line 5))
Requirement already satisfied: appdirs>=1.4.0 in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from setuptools->jsonschema==3.0.1->-r requirements.txt (line 5))
Requirement already satisfied: packaging>=16.8 in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from setuptools->jsonschema==3.0.1->-r requirements.txt (line 5))
Requirement already satisfied: pyparsing in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from packaging>=16.8->setuptools->jsonschema==3.0.1->-r requirements.txt (line 5))
Building wheels for collected packages: pyrsistent
  Running setup.py bdist_wheel for pyrsistent ... done
  Stored in directory: /home/travis/.cache/pip/wheels/83/59/9a/a037b9b3c3e93d9275ea0aff9d6064400f372879dfdab01afe
Successfully built pyrsistent
Installing collected packages: six, pyrsistent
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Rolling back uninstall of six
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2813, in _dep_map
    return self.__dep_map
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info
    return self._pkg_info
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/dist.py", line 321, in __init__
    _Distribution.__init__(self, attrs)
  File "/opt/python/3.4.6/lib/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/dist.py", line 389, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/six-1.10.0.dist-info/METADATA'
The command "pip install -r requirements.txt" failed and exited with 2 during .
Your build has been stopped.

Signed-off-by: Heikki Laaksonen <laaksonen.heikki.j@gmail.com>