Fix exception with empty --scat command line option
If user did not give any value to the --scat command line
option, the results was crash [1]. Now the result is an
error text that requires at least one argument for the
option.

The problem was that an empty list was accepted as an
argument. This caused exception [1].

[1]
Traceback (most recent call last):
  File "runner", line 7, in <module>
    snippy.snip.main()
  File "/work/samba/snippy/snippy/snip.py", line 129, in main
    snippy = Snippy(args)
  File "/work/samba/snippy/snippy/snip.py", line 40, in __init__
    Config.init(args)
  File "/work/samba/snippy/snippy/config/config.py", line 135, in init
    cls.source = Cli(args)
  File "/work/samba/snippy/snippy/config/source/cli.py", line 146, in __init__
    self._read_conf(args)
  File "/work/samba/snippy/snippy/config/source/cli.py", line 308, in _read_conf
    self.init_conf(arguments)
  File "/work/samba/snippy/snippy/config/source/base.py", line 229, in init_conf
    self.category = parameters.get('category', Const.SNIPPET)
  File "/work/samba/snippy/snippy/config/source/base.py", line 322, in category
    value = value[0]
IndexError: tuple index out of range

Signed-off-by: Heikki Laaksonen <laaksonen.heikki.j@gmail.com>