Edit Python module versions for Pipenv
Pipenv virtual environment versions were updated. The file
is intended for Python 3.7 because that is the main devel
environment currently used by the author.

This was tested with pipenv 2020.4.1b1.

The Pylint and Pyflakes were not updated because there is
a conflict when running Pylint with latest versions. Root
cause for this is not known

  $ make lint
  Traceback (most recent call last):
    File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib/python3.7/site-packages/pylint/__main__.py", line 18, in <module>
      pylint.run_pylint()
    File "/root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
      PylintRun(sys.argv[1:])
    File "/root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib/python3.7/site-packages/pylint/lint/run.py", line 338, in __init__
      linter.check(args)
    File "/root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 878, in check
      files_or_modules,
    File "/root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib/python3.7/site-packages/pylint/lint/check_parallel.py", line 101, in check_parallel
      _worker_check_single_file, files
    File "/usr/lib64/python3.7/multiprocessing/pool.py", line 748, in next
      raise value
  ImportError: Unable to find module for tests/conftest.py in /usr/lib64/python37.zip,
  /usr/lib64/python3.7,
  /usr/lib64/python3.7/lib-dynload,
  /root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib64/python3.7/site-packages,
  /root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib/python3.7/site-packages,
  /root/.cache/snippy/.virtualenvs/snippy-bx98gM5i/lib/python3.7/site-packages/astroid/brain
  make: *** [Makefile:111: lint] Error 1

Signed-off-by: Heikki Laaksonen <laaksonen.heikki.j@gmail.com>